### ISSUE TITLE
About Normalized MultiWoz Dataset,

### ISSUE THREAD

**Issue by jeonggwanlee** [snakeztc/NeuralDialog-LaRL#2]
Hi, 
Thank you for sharing your code.

I wondered how did you normalize MultiWoz dataset.

For example, class "NormMultiWozCorpus" in latent_dialog/corpora.py,
bs_size = 94,
db_size = 30,
db_types = ['b', 'c']

Could you explain how 'bs_size' is 94, 'db_size' is 30, and what 'b' and 'c' means?  

and could you share the overall process of normalizing?
(If you can share your pre-process code, It's very helpful.)

**Comment by snakeztc** [comment]
I use the same script from the original repo of MWoz 2.0.  https://github.com/budzianowski/multiwoz

**Comment by jeonggwanlee** [comment]
@snakeztc  Thank you for your quick reply!

I can check repo of MWoz 2.0. https://github.com/budzianowski/multiwoz
